### PR TITLE
add feature: access token copy from UI

### LINKED ISSUE #7: Quick access to access token
**Is your feature request related to a problem? Please describe.**

Often we need a Krini-scoped LS AAI access token for test purposes, `curl` requests etc. Currently, this requires logging in to LS AAI via Krini, then checking out the ELIXIR AAI token endpoint at https://login.elixir-czech.org/oidc/manage/user/tokens. It would be nice if the token was accessible from the Krini UI itself after login.

**Describe the solution you'd like**

Add a menu point "Copy access token" to the user config in the upper right corner (between "Profile" and "Log out"). When clicking/tapping it, copy the value of the token to the clipboard and show a message informing the user that the token value has been copied to the clipboard.

### PR DESCRIPTION
**Pull request by tanya17-05**
Closes #7 
`Copy to clipboard` option available to copy the access token after `profile` option and before `logout` option 

Before 
pre
After
post

### CODE REVIEW

**Review by uniqueg — CHANGES_REQUESTED** [review]
Looks great to me :) One minor thing: The menu item should say "Copy token to clipboad", currently it's not clear _what_ is being copied to the clipboard

**Comment by uniqueg** [comment]
@tanya17-05: On second thought, perhaps it's better to actually name it "Copy access token" as it's more descriptive and shorter. If I read your code well, then users will get a notification that it's been copied _to the clipboard_ once they select the option - which is good enough.

Sorry about that :)

**Comment by uniqueg** [comment]
Afterwards, can you please review @git-anurag-hub and, if you don't have any issues, merge? 🙏

**Comment by tanya17-05** [comment]
No problem @uniqueg :)

**Review by uniqueg — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
LG!

**Pull request merged**
