### PR TITLE
feat: tes integration

### LINKED ISSUE #23: feat: integration of TES components in Krini
The integration of the TES components into Krini has become a smoother process. Here are the key steps involved:

- Packaging & Deployment: Successfully packaged and deploy the TES component library as a pre-release version on NPM. This ensures that the components are readily available for integration.

- Configuration Update: To complete the integration, remove the old Krini configuration and replaced it with the new TES components. This update aligns Krini with the latest component library, enhancing its functionality and user experience.

- Extended Functionality: In addition to the core integration, we have an extended goal. We aim to replace the LS AAI login button by leveraging the new component. This allows us to abstract and centralize common logic, making our codebase more maintainable and efficient. You can track the progress of this goal in the pending pull request here: [GitHub PR #67](https://github.com/elixir-cloud-aai/cloud-components/pull/67).

These steps signify a significant improvement in the ease of integrating TES components into Krini.

### PR DESCRIPTION
**Pull request by JaeAeich**
**Details**

This PR deals with the integration of the TES Web Component.

**Closing issues**

closes #23

### CODE REVIEW

**Comment by JaeAeich** [comment]
@git-anurag-hub Can you check this out?
- Firstly, I have given an arbitrary margin to the component that came under the navbar, Is this how am I supposed to do it?
- The component renders, but it doesn't call the API on rendering, but when I force it by clicking on next (pagination) it works.
-  What API to actually pass here? Do I need to perform any admin checks etc like passign `admin=true` attr.

**Comment by JaeAeich** [comment]
@git-anurag-hub I think the deployment of this is not right, it should redirect me to the deployment of this branch after login but it sends me to the dep of the main branch. I don't think I can configuree that from here, please look into that as well.

**Comment by git-anurag-hub** [comment]
> @git-anurag-hub I think the deployment of this is not right, it should redirect me to the deployment of this branch after login but it sends me to the dep of the main branch. I don't think I can configuree that from here, please look into that as well.

Yeah that will be hard to configure i guess as the redirect can only be set by the OIDC LS portal & the deployment url will be dynamic for each pr!

**Comment by JaeAeich** [comment]
- TESRuns component doesn't fetch immediately to be fixed in #27 .
- By default it is using TESK TES API, need to test against proTES.

**Comment by git-anurag-hub** [comment]
Thanks @JaeAeich, so we can merge this then?

**Comment by JaeAeich** [comment]
@git-anurag-hub please review this branch and merge.

**Review by git-anurag-hub — APPROVED** [review]
LGTM!

**Pull request merged**
